apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-datasets
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  hostPath:
      path: /pv/data-store