apiVersion: v1
kind: Namespace
metadata:
  name: my-namespace

---

apiVersion: v1
data:
  TIME_FREQ: "5"
kind: ConfigMap
metadata:
  name: time-config
  namespace: my-namespace

---

apiVersion: v1
kind: Pod
metadata:
  labels:
    run: time-check
  name: time-check
  namespace: my-namespace
spec:
  volumes:
  - name: log-volume
    emptyDir: {}
  containers:
  - image: busybox
    name: time-check
    env:
    - name: TIME_FREQ
      valueFrom:
            configMapKeyRef:
              name: time-config
              key: TIME_FREQ
    volumeMounts:
    - mountPath: /opt/time
      name: log-volume
    command:
    - "/bin/sh"
    - "-c"
    - "while true; do date | tee -a /opt/time/time-check.log; sleep $TIME_FREQ; done"
