apiVersion: v1
kind: Namespace
metadata:
  name: my-namespace

---

apiVersion: v1
kind: Pod
metadata:
  labels:
    run: testerapp
  name: testerapp
  namespace: my-namespace
spec:
  containers:
  - image: truebad0ur/testerapp:v2
    imagePullPolicy: IfNotPresent
    name: testapp
    livenessProbe:
      exec:
        command:
        - ls
        - /bin/application
      initialDelaySeconds: 5
      periodSeconds: 5
    readinessProbe:
      exec:
        command:
        - ls
        - /tmp/test
      initialDelaySeconds: 5
      periodSeconds: 5
