apiVersion: v1
kind: Namespace
metadata:
  name: my-namespace

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-claim
  namespace: my-namespace
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 200Mi
  storageClassName: standard

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
  name: redis-depl
  namespace: my-namespace
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: redis:alpine
        name: redis
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: /data
          name: redis-data
        resources:
          requests:
            cpu: "0.2"
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-claim
