apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: my-namespace
data:
  filename1: c3VwZXJzZWNyZXRkYXRh
  fileaname2: c2Vjb25kc3VwZXJjb29sc2VjcmV0
---

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: secret-busybox
  name: secret-busybox
  namespace: my-namespace
spec:
  volumes:
  - name: secret-volume
    secret:
      secretName: my-secret
  nodeSelector:
    #kubernetes.io/hostname: controlplane
    kubernetes.io/hostname: mycluster
  tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
  containers:
  - command:
    - sleep
    args:
    - "3600"
    image: busybox
    name: secret
    volumeMounts:
    - name: secret-volume
      readOnly: true
      mountPath: "/etc/secret-volume"
