apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: omega-apps
  name: omega-apps
spec:
  replicas: 3
  selector:
    matchLabels:
      app: omega-apps
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: omega-apps
    spec:
      affinity:
        nodeAffinity:
         requiredDuringSchedulingIgnoredDuringExecution:
           nodeSelectorTerms:
           - matchExpressions:
             - key: app_type
               values: ["omega"]
               operator: In
      containers:
      - image: nginx
        name: nginx