apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sigma
  name: sigma
spec:
  tolerations:
  - effect: NoSchedule
    key: app_type
    value: sigma
  containers:
  - image: redis
    name: sigma
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

# kubectl run sigma --image=redis --dry-run=client -oyaml > sigma.yaml