apiVersion: v1
kind: Pod
metadata:
  labels:
    name: webapp-rockets
  name: webapp-rockets
  namespace: default
spec:
  containers:
  - env:
    - name: ROCKET_SIZE
      value: big
    image: rotorocloud/simple-webapp-rockets
    imagePullPolicy: Always
    name: webapp-rockets