apiVersion: v1
kind: Pod
metadata:
  name: nginx3003
  namespace: default
spec:
  containers:
    - name: nginx3003
      image: nginx
      livenessProbe:
        exec:
          command: ["ls /var/www/html/probe"]
        initialDelaySeconds: 10
        periodSeconds: 60