apiVersion: batch/v1
kind: CronJob
metadata:
  name: random
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      completions: 1
      backoffLimit: 25 # This is so the job does not quit before it succeeds.
      activeDeadlineSeconds: 20
      template:
        spec:
          containers:
          - name: error-gen
            image: rotorocloud/error-gen
          restartPolicy: Never